/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface ProductEntity {
  'category_category_id': number;
  'product_details': string | null;
  'product_discount': number | null;
  'product_id': number;
  'product_image': string | null;
  'product_money': number | null;
  'product_name': string | null;
  'product_sku': string | null;
  'product_weight': number | null;
}


export const ProductAttributes = [
    "category_category_id",
    "product_details",
    "product_discount",
    "product_id",
    "product_image",
    "product_money",
    "product_name",
    "product_sku",
    "product_weight"
];