/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface RowsEntity {
  'id'?: number;
  'name_row': string | null;
}


export const RowsAttributes = [
    "id",
    "name_row"
];