/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface TopicprojectEntity {
  'id': number;
  'work': string | null;
}


export const TopicprojectAttributes = [
    "id",
    "work"
];