/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface UserdataEntity {
  'email': string | null;
  'id'?: number;
  'image': string;
  'password': string | null;
  'Position': string | null;
  'Username': string | null;
  'user_role': number | null;
}


export const UserdataAttributes = [
    "email",
    "id",
    "image",
    "password",
    "Position",
    "Username",
    "user_role"
];