/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface UserEntity {
  'id'?: number;
  'Username': string | null;
}


export const UserAttributes = [
    "id",
    "Username"
];