/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface WorkloadEntity {
  'date': string | null;
  'details': string | null;
  'id'?: number;
  'time': string | null;
  'user_id': number | null;
  'work_id': number | null;
}


export const WorkloadAttributes = [
    "date",
    "details",
    "id",
    "time",
    "user_id",
    "work_id"
];